import Link from 'next/link'
import { getPosts } from '../utils/mdxUtils'

export default function Index() {
  const posts = getPosts()

  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath.replace(/\.mdx?$/, '')}`}
              href={`/posts/[slug]`}
            >
              {post.frontmatter.title}
            </Link>
          </li>
        ))}
      </ul>
    </>
  )
}
